"""
Phase 8: Scale to 10M Songs (Streaming Embedding Generation)
============================================================

Reads the raw chunked features generated by `prepare_10m_features.py`,
processes them through the trained `SongEncoder` in batches, and writes
the 64-dimensional learned embeddings to a memmap or raw binary file.

Because 10M * 64 * 4 bytes = ~2.5 GB, we can safely memmap this on most systems.
"""

import os
import argparse
import time
import numpy as np
import torch
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset

from src.models.song_encoder import SongEncoder

def generate_10m_embeddings(
    features_path: str,
    index_path: str,
    model_dir: str,
    out_embeddings_path: str,
    batch_size: int = 16384,
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
):
    print("=" * 60)
    print("PHASE 8: GENERATING 10M EMBEDDINGS (STREAMING)")
    print("=" * 60)
    
    # 1. Load Metadata to know exact size
    print(f"Loading metadata from {index_path}...")
    meta_df = pd.read_parquet(index_path)
    num_songs = len(meta_df)
    print(f"Total songs to encode: {num_songs:,}")
    
    # 2. Open Raw Features File
    feature_dim = 13
    print(f"Loading features from {features_path}...")
    # Using memmap to avoid loading 10M * 13 floats into memory at once if it was large
    # (Though 10M * 13 * 4 is ~520MB, completely fine for RAM, memmap is best practice for scale)
    features_mmap = np.memmap(features_path, dtype=np.float32, mode='r', shape=(num_songs, feature_dim))
    
    # 3. Load Model
    print(f"Loading SongEncoder from {model_dir}...")
    model = SongEncoder.load(model_dir).to(device)
    model.eval()
    
    # 4. Prepare Output Memmap
    os.makedirs(os.path.dirname(out_embeddings_path), exist_ok=True)
    out_dim = model.network[-1].out_features
    print(f"Creating output memmap {out_embeddings_path} (shape: {num_songs} x {out_dim})...")
    out_mmap = np.memmap(out_embeddings_path, dtype=np.float32, mode='w+', shape=(num_songs, out_dim))
    
    # 5. Batch Inference
    print(f"Generating embeddings using {device} (batch_size={batch_size})...")
    start_time = time.time()
    
    with torch.no_grad():
        for start_idx in range(0, num_songs, batch_size):
            end_idx = min(start_idx + batch_size, num_songs)
            
            # Read chunk from mmap
            batch_features = features_mmap[start_idx:end_idx]
            batch_tensor = torch.from_numpy(batch_features).to(device)
            
            # Encode
            embeddings = model(batch_tensor).cpu().numpy()
            
            # Write to output mmap
            out_mmap[start_idx:end_idx] = embeddings
            
            if (start_idx // batch_size) % 10 == 0:
                print(f"  Processed {end_idx:,} / {num_songs:,} ...")
                
    # Flush to disk
    out_mmap.flush()
    elapsed = time.time() - start_time
    
    size_mb = os.path.getsize(out_embeddings_path) / (1024 * 1024)
    print(f"Embeddings saved to {out_embeddings_path} ({size_mb:.2f} MB)")
    print(f"Total inference time: {elapsed:.2f} seconds.")
    print("=" * 60)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--features", type=str, default="data/processed/10m/content_features_10m.raw")
    parser.add_argument("--index", type=str, default="data/processed/10m/song_index_10m.parquet")
    parser.add_argument("--model_dir", type=str, default="models/song_encoder_v1")
    parser.add_argument("--out_embeddings", type=str, default="data/processed/10m/song_embeddings_10m.npy")
    parser.add_argument("--batch_size", type=int, default=16384)
    
    args = parser.parse_args()
    
    if not os.path.exists(args.features):
        print(f"Skip generating: {args.features} not found.")
    else:
        generate_10m_embeddings(
            args.features,
            args.index,
            args.model_dir,
            args.out_embeddings,
            args.batch_size
        )
